---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-info
  template:
    metadata:
      labels:
        app: pod-info
    spec:
      containers:
      - name: pod-info
        image: docker.io/aryansr/podinfoapp:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: pod-info-service
spec:
  selector:
    app: pod-info
  ports:
  - port: 80
    targetPort: 3000
